on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.OS }}

    strategy:
      matrix:
        OS: [ubuntu-24.04]
        lisp: [sbcl_static]
      fail-fast: false
    runs-on: ${{ matrix.OS }}

    # NOTE: PWD = GITHUB_WORKSPACE = /home/runner/work/cl-repl/cl-repl = ~/work/cl-repl/cl-repl
    #       HOME = /home/runner

    steps:

    - uses: actions/checkout@v4

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
        OS:   ${{ matrix.OS }}
      run: |
        pwd
        ls -l
        bash --version
        bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)

    - name: Compile isocline
      run: |
        pwd
        cd isocline/
        mkdir -p build/release
        cd build/release
        cmake ../..
        cmake --build .

    - name: Statically link against libisocline + libcrypto, libssl, libtls
      run: |
        sudo apt install -y libssl-dev libtls-dev
        SBCL_DIR="sbcl-2.6.3+r00-x86-64-linux"
        SYS_LIBDIR="/usr/lib/x86_64-linux-gnu"
        LIBCRYPTO=${SYS_LIBDIR}/libcrypto.a
        LIBSSL=${SYS_LIBDIR}/libssl.a
        LIBTLS=${SYS_LIBDIR}/libtls.a
        LIBISOCLINE="$PWD/isocline/build/release/libisocline.a"
        export WHOLE_ARCHIVES="-Wl,--whole-archive $LIBCRYPTO $LIBSSL $LIBTLS $LIBISOCLINE"
        cd "/home/runner/$SBCL_DIR"
        make -C "src/runtime" -f binaries.mk sbcl.extras
        mv "src/runtime/sbcl.extras" "src/runtime/sbcl"

    - name: Dump lisp image
      run: |
        cl --load isocline-repl.asd \
           --load isocline.asd \
           --eval '(ql:quickload :isocline-repl)' \
           --eval "(cffi:close-foreign-library 'isocline::libisocline)"\
           --eval '(asdf:make "isocline-repl")' \
           --quit

        
    - name: Set release name
      run: echo "IC_REPL_DIR=cl-isocline-repl.${{ matrix.OS }}.$(uname -m)" >> $GITHUB_ENV

    - name: Rename lisp image and copy licenses
      run: |
        mkdir ${{ env.IC_REPL_DIR }}
        mv cl-isocline-repl ${{ env.IC_REPL_DIR }}/${{ env.IC_REPL_DIR }}.bin
        cp -r /home/runner/sbcl-2.6.3+r00-x86-64-linux/COPYING* ${{ env.IC_REPL_DIR }}
        sudo apt install -y atool
        apack ${{ env.IC_REPL_DIR }}.tar.gz ${{ env.IC_REPL_DIR }}/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.IC_REPL_DIR }}
        path: ${{ env.IC_REPL_DIR }}
        compression-level: 0

    - name: Upload asset to 'latest' release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete latest --yes --cleanup-tag
        gh release create latest *.tar.gz
