on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.OS }}

    strategy:
      matrix:
        OS: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel]
        lisp: [sbcl_static]
      fail-fast: false
    runs-on: ${{ matrix.OS }}

    # NOTE: PWD = GITHUB_WORKSPACE = /home/runner/work/cl-repl/cl-repl = ~/work/cl-repl/cl-repl
    #       HOME = /home/runner

    steps:

    - uses: actions/checkout@v4

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
        OS:   ${{ matrix.OS }}
      run: |
        pwd
        ls -l
        case $(uname -m) in
            x86_64) ARCH="x86-64" ;;
            arm64|aarch64) ARCH="arm64";;
            *) ARCH=$(uname -m) ;;
        esac
        echo "ARCH=${ARCH}" >> ${GITHUB_ENV}
        bash --version
        bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)

    - name: Compile isocline
      run: |
        pwd
        cd isocline/
        mkdir -p build/release
        cd build/release
        cmake ../..
        cmake --build .

    - name: Install libssl libtls
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]' )
        echo "OS=${OS}" >> ${GITHUB_ENV}
        if [ "$OS" == "linux" ]; then
            sudo apt install -y openssl libssl-dev libtls-dev atool
        elif [ "$OS" == "darwin" ]; then
            brew install openssl libretls atool
        fi

    - name: Statically link against libisocline + libcrypto, libssl, libtls
      run: |
        case ${OS} in
            linux) SYS_LIBDIR="/usr/lib/" ;;
            darwin) SYS_LIBDIR="$(brew --prefix)" ;;
        esac

        LIBCRYPTO=$(find $SYS_LIBDIR -name "libcrypto.a" | head -1)
        LIBSSL=$(find $SYS_LIBDIR -name "libssl.a" | head -1)
        LIBTLS=$(find $SYS_LIBDIR -name "libtls.a" | head -1)
        LIBISOCLINE="$PWD/isocline/build/release/libisocline.a"

        if [ "$OS" == "linux" ]; then
            SBCL_DIR="/home/runner/sbcl-2.6.3+r00-$ARCH-$OS"
            export WHOLE_ARCHIVES="-Wl,--whole-archive $LIBCRYPTO $LIBSSL $LIBTLS $LIBISOCLINE"
        elif [ "$OS" == "darwin" ]; then
            SBCL_DIR="/Users/runner/sbcl-2.6.3+r00-$ARCH-$OS"
            # -force_load only works on one library at a time
            export WHOLE_ARCHIVES="-Wl,-force_load $LIBCRYPTO -Wl,-force_load $LIBSSL -Wl $LIBTLS -Wl,-force_load $LIBISOCLINE"
        fi

        cd "$SBCL_DIR"
        make -C "src/runtime" -f binaries.mk sbcl.extras
        mv "src/runtime/sbcl.extras" "src/runtime/sbcl"
        echo "SBCL_DIR=${SBCL_DIR}" >> ${GITHUB_ENV}

    - name: Dump lisp image
      run: |
        cl --load isocline-repl.asd \
           --load isocline.asd \
           --eval '(ql:quickload "isocline-repl")' \
           --eval "(cffi:close-foreign-library 'isocline::libisocline)"\
           --eval '(asdf:make "isocline-repl")' \
           --quit

    - name: Dump lisp image with CIEL
      continue-on-error: true
      run: |
        cl --load isocline-repl+ciel.asd \
           --load isocline-repl.asd \
           --load isocline.asd \
           --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' \
           --eval '(ql:quickload "isocline-repl+ciel")' \
           --eval "(cffi:close-foreign-library 'isocline::libisocline)"\
           --eval "(cl:in-package :ciel-user)" \
           --eval '(asdf:make "isocline-repl+ciel")' \
           --quit

    - name: Set release name
      run: |
        echo "IC_REPL_DIR=cl-isocline-repl.${OS}.${ARCH}" >> $GITHUB_ENV
        echo "IC_REPL_CIEL_DIR=cl-isocline-repl+ciel.${OS}.${ARCH}" >> $GITHUB_ENV

    - name: Rename base lisp image and copy licenses
      run: |
        mkdir ${{ env.IC_REPL_DIR }}
        mv cl-isocline-repl ${{ env.IC_REPL_DIR }}/${{ env.IC_REPL_DIR }}.bin
        cp -r ${SBCL_DIR}/COPYING* ${{ env.IC_REPL_DIR }}
        apack ${{ env.IC_REPL_DIR }}.tar.gz ${{ env.IC_REPL_DIR }}/*

    - name: Rename lisp image with CIEL and copy licenses
      continue-on-error: true
      run: |
        mkdir ${{ env.IC_REPL_CIEL_DIR }}
        mv cl-isocline-repl+ciel ${{ env.IC_REPL_CIEL_DIR }}/${{ env.IC_REPL_CIEL_DIR }}.bin
        cp -r ${SBCL_DIR}/COPYING* ${{ env.IC_REPL_CIEL_DIR }}
        apack ${{ env.IC_REPL_CIEL_DIR }}.tar.gz ${{ env.IC_REPL_CIEL_DIR }}/*

    - name: Upload asset to 'latest' release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch --all -t
        LATEST_SHA=$(git rev-parse latest)
        CURRENT_SHA=$(git rev-parse HEAD)
        echo "Latest: " $LATEST_SHA
        echo "Current: " $CURRENT_SHA
        if [ "$LATEST_SHA" == "$CURRENT_SHA" ]; then
            gh release upload latest *.tar.gz
        else
            gh release delete latest --yes --cleanup-tag
            gh release create latest *.tar.gz
        fi
